# 
# |  6   |  7  |   8   |   9   |   10  |   11  |   12  |  13  |  14  |   15  |  16  |   17   |  18 |  19  |  20  |  21 |  22  |  23  |
# |  1h  |  2h | marks | block | smith | heavy | light | pick | lock | sneak | alch | speech | alt | conj | dest | ill | rest | ench |
# 
# Strength = 1, two handed damage, fire resistance, shock resistance, medium carry bonus
# Intelligence = 2, spell power, spell duration
# Willpower = 3, mana pool, magic resistance, mana regeneration bonus
# Agility = 4, one handed damage, poison resistance, small carry bonus
# Speed = 5, stamina pool, ranged damage
# Endurance = 6, health, disease resistance, frost resistance, great carry bonus
# Personality = 7, armor, stamina regeneration
# Luck = 8, luck
# Faith = 9, Praise the Sun
# None = 10
#
# id = unique spec name
# description = translatable text from interface/translations/SDS_lang.txt
# focus = not used rn
# attr1, attr2 = favourite spec attributes
# skils = primary spec skills, max 6
# 

[[class]]
id = "Acrobat"
description = "$AcrobatDesc"
focus = 3
attr1 = 4
attr2 = 6
skills = [6, 8, 9, 14, 15, 17]
equipment = "0x000809|SDSInterface.esp"

[[class]]
id = "Agent"
description = "$AgentDesc"
focus = 3
attr1 = 4
attr2 = 7
skills = [8, 13, 14, 15, 17, 21]
visible = false
equipment = "0x00080A|SDSInterface.esp"

[[class]]
id = "Archer"
description = "$ArcherDesc"
focus = 1
attr1 = 1
attr2 = 4
skills = [6, 8, 10, 12, 15, 16]
visible = false
equipment = "0x00080B|SDSInterface.esp"

[[class]]
id = "Assassin"
description = "$AssassinDesc"
focus = 3
attr1 = 2
attr2 = 5
skills = [6, 8, 12, 14, 15, 16]
equipment = "0x00080C|SDSInterface.esp"

[[class]]
id = "Barbarian"
description = "$BarbarianDesc"
focus = 1
attr1 = 1
attr2 = 5
skills = [6, 7, 9, 10, 12, 17]
equipment = "0x00080D|SDSInterface.esp"

[[class]]
id = "Bard"
description = "$BardDesc"
focus = 3
attr1 = 2
attr2 = 7
skills = [6, 9, 12, 16, 17, 21]
equipment = "0x00080E|SDSInterface.esp"

[[class]]
id = "Battlemage"
description = "$BattlemageDesc"
focus = 2
attr1 = 1
attr2 = 2
skills = [6, 11, 16, 18, 19, 20]
equipment = "0x00080F|SDSInterface.esp"

[[class]]
id = "Crusader"
description = "$CrusaderDesc"
focus = 1
attr1 = 1
attr2 = 3
skills = [6, 9, 10, 11, 20, 22]
equipment = "0x000810|SDSInterface.esp"

[[class]]
id = "Healer"
description = "$HealerDesc"
focus = 2
attr1 = 3
attr2 = 7
skills = [16, 17, 18, 20, 21, 22]
equipment = "0x000811|SDSInterface.esp"

[[class]]
id = "Knight"
description = "$KnightDesc"
focus = 1
attr1 = 1
attr2 = 7
skills = [6, 9, 10, 11, 17, 21]
equipment = "0x000812|SDSInterface.esp"

[[class]]
id = "Mage"
description = "$MageDesc"
focus = 2
attr1 = 2
attr2 = 3
skills = [18, 19, 20, 21, 22, 23]
equipment = "0x000813|SDSInterface.esp"

[[class]]
id = "Nightblade"
description = "$NightbladeDesc"
focus = 2
attr1 = 3
attr2 = 5
skills = [6, 12, 15, 18, 20, 22]
equipment = "0x000814|SDSInterface.esp"

[[class]]
id = "Outlander"
description = "$OutlanderDesc"
focus = -1
attr1 = -1
attr2 = -1
skills = [-1, -1, -1, -1, -1, -1]
equipment = "0x000815|SDSInterface.esp"

[[class]]
id = "Pilgrim"
description = "$PilgrimDesc"
focus = 3
attr1 = 6
attr2 = 7
skills = [6, 7, 9, 10, 12, 17]
equipment = "0x000816|SDSInterface.esp"

[[class]]
id = "Rogue"
description = "$RogueDesc"
focus = 1
attr1 = 5
attr2 = 7
skills = [6, 9, 12, 16, 17, 21]
equipment = "0x000817|SDSInterface.esp"

[[class]]
id = "Scout"
description = "$ScoutDesc"
focus = 1
attr1 = 5
attr2 = 6
skills = [6, 9, 10, 12, 16, 14]
equipment = "0x000818|SDSInterface.esp"

[[class]]
id = "Sorcerer"
description = "$SorcererDesc"
focus = 2
attr1 = 2
attr2 = 6
skills = [11, 16, 18, 19, 20, 22]
equipment = "0x000819|SDSInterface.esp"

[[class]]
id = "Spellsword"
description = "$SpellswordDesc"
focus = 2
attr1 = 3
attr2 = 6
skills = [6, 9, 18, 20, 21, 22]
equipment = "0x00081A|SDSInterface.esp"

[[class]]
id = "Thief"
description = "$ThiefDesc"
focus = 3
attr1 = 4
attr2 = 5
skills = [8, 12, 13, 14, 15, 17]
equipment = "0x00081B|SDSInterface.esp"

[[class]]
id = "Warrior"
description = "$WarriorDesc"
focus = 1
attr1 = 1
attr2 = 6
skills = [6, 7, 9, 10, 11, 12]
equipment = "0x00081C|SDSInterface.esp"

[[class]]
id = "Witchhunter"
description = "$WitchhunterDesc"
focus = 2
attr1 = 2
attr2 = 4
skills = [8, 12, 16, 19, 20, 23]
equipment = "0x00081D|SDSInterface.esp"

[racialBonuses]
# Argonian
0x13740 = [0, 5, -5, 5, 5, -10, -10, 0, 0]
# Breton
0x13741 = [-5, 10, 10, -10, -5, -10, 0, 0, 0]
# Dark Elf
0x13742 = [0, 0, -10, 0, 10, -5, -5, 0, 0]
# High Elf
0x13743 = [-10, 10, 0, 0, -5, -5, 0, 0, 0]
# Imperial
0x13744 = [0, 0, -5, -10, -5, 0, 10, 0, 0]
# Khajiit
0x13745 = [-5, 0, -10, 10, 0, -5, 0, 0, 0]
# Nord
0x13746 = [10, -10, -5, 0, 0, 5, -10, 0, 0]
# Orc
0x13747 = [5, -5, 5, -5, -10, 10, -15, 0, 0]
# Redguard
0x13748 = [5, -10, -10, 0, 0, 10, -5, 0, 0]
# Wood Elf
0x13749 = [-10, 0, -10, 10, 10, -5, -5, 0, 0]

[generalSettings]
actionColor = "#eaeaea"
entryColor = "#c4c4c4"
statColor = "#bbbcad"
titleColor = "#A5987F"
textColor = "#c1c2b2"
subTitleColor = "#c0b194"
negativeChangeColor = "#ae2127"
positiveChangeColor = "#3c61b3"
bDebugEnabled = 1
iLogLevel = 1
sTravelActivatorKW = "0x0965B2|Skyrim.esm"
sTeleportQuestID = "0x005902|Rebalance.esp"
# pointforward, pointup, pointdown, wave, study, joy, bow, rest
emoteListStart = ["IdlePointFar_02", "idlepointclose", "idlecomethisway", "idlewave", "idlestudy", "idlelaugh", "idlesilentbow", "IdleSitCrossLeggedEnter"]

[menuList]
bRaceMenu = 1
bLevelUpMenu = 1
bTweenMenu = 1
bBonfireMenu = 1
bTravelMenu = 0
bEmotesMenu = 1

[levelingSettings]
# limit how many times skill can be increased per level
iMaxLevelsPerSkillPerPlayerLevel = 5
# skill point costs per level
iSkillPointCost0 = 3
iSkillPointCost25 = 5
iSkillPointCost50 = 7
iSkillPointCost75 = 9
fSkillPointsLevelMultiplier = 1.5
iSkillPointsPerLevel = 15
iAttributePointsPerLevel = 3
# max value how many skill points player can get per level
iSkillPointsCap = 45
# Starting Attribute value when character first created to apply all bonuses into
iBaseAttributeValue = 20
iClassBaseAttributeBonus = 5
iClassBaseSkillBonus = 5
iAttributeCap = 100

[Strength.FireResist]
1 = 0.05

[Strength.ElectricResist]
1 = 0.05

[Strength.CarryWeight]
1 = 0.50

[Willpower.Magicka]
1 = 3.5

[Willpower.MagicResist]
1 = 0.05

[Willpower.MagickaRateMult]
1 = 1.0

[Agility.PoisonResist]
1 = 0.05

[Agility.CarryWeight]
1 = 0.25

[Speed.Stamina]
1 = 3.5

[Endurance.Health]
1 = 3.5

[Endurance.FrostResist]
1 = 0.05

[Endurance.DiseaseResist]
1 = 0.05

[Endurance.CarryWeight]
1 = 1.5

[Personality.DamageResist]
1 = 0.25

[Personality.StaminaRateMult]
1 = 0.5
